[package]
name = "astra-gui-interactive"
version.workspace = true
edition.workspace = true
description = "Interactive components library for astra-gui"

[dependencies]
astra-gui = { workspace = true }
astra-gui-wgpu = { workspace = true }
astra-gui-macros = { workspace = true }
